version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sergh3110Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  version: "1.0"
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
- name: GithubPackageDebuglog
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.sergh3110.integrations:azrepoPackage
  packages:
  - name: Sergh3110Project
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: GithubPackageDebuglog
    version: "3.0"
- serviceName: AddIntsPackage:addIntsFS
  packages:
  - name: AddIntsPackage
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2100
